### ISSUE TITLE
AD through `warp`

### ISSUE THREAD

**Issue by SomTambe** [SomTambe/DiffImages.jl#12]
This issue is for tracking the progress of enabling **AD through `ImageTransformations.warp`**.
**author**: @SomTambe 
**mentors**: @DhairyaLGandhi @johnnychen94 
## Background
[`ImageTransformations.jl`](https://github.com/JuliaImages/ImageTransformations.jl) implements a backward mode warp, which performs the exact operations as elaborated in #11 . The target would be to get the gradient with respect to the input warp matrix `W`, and as  a long term goal, also the input image `X`.
## Roadmap
- [x] Implement adjoints for `_getindex`
- [x] Implement adjoints for `BSplines` and `Extrapolations`.
- [x] Implement adjoints for `SMatrix` and `SVector`.
- [x] Write rrule for `homography` struct.
- [x] Write tests to check individual gradients in pipeline using FiniteDifferences.
- [x] Write tests to check gradient of whole pipeline using FiniteDifferences.
- [x] Make sure the index-wise gradients are correct.
- [x] Make sure the individual gradients are correct in the pipeline.
- [x] Make sure accumulated gradients for the whole image are correct.
- [x] Train the parameters of a homography matrix using the local warp function.
- [x] Extend the current adjoints to write a complete adjoint for the `ImageTransformations.warp!`
- [x] Train the parameters of a homography matrix using the `ImageTransformations.warp` function.

**Comment by DhairyaLGandhi** [comment]
> Make sure the index-wise gradients are correct.
  Make sure the individual gradients are correct in the pipeline.
  Make sure accumulated gradients for the whole image are correct.

Can we get tests in for these

**Comment by SomTambe** [comment]
yeah sure, I'm in the process of making the new branch and creating a PR

**Comment by johnnychen94** [comment]
Ad though `warp` task can be separated into at least four steps:

1. AD through the backward coordinate map `ϕ`. Homography matrix and other existing types from CoordinateTransformations are good candidates for this.
2. AD though the value estimator `τ`. Since we use the interpolation/extrapolation family, we need to interact with Interpolations.jl properly and find out potential missing items.
3. verify the warp operation on single-pixel works
4. composite the high-order `warp` on the full image scale
